name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install
        run: yarn
      - name: Serve
        run: yarn develop
      - name: Percy Test
        uses: percy/exec-action@v0.3.0
        with:
          command: "cypress run --spec 'cypress/integration/percy/visual.spec.js'"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}